# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SP 101 - 008 UA Fall 2016
email: jmbeach1@crimson.ua.edu
description: > # this means to ignore newlines until "baseurl:"
  Website for notes and resources from Spanish 101 at The University
  of Alabama Fall 2016;
baseurl: "/SP101-008" # the subpath of your site, e.g. /blog
url: "http://jmbeach.github.io/SP101-008" # the base hostname & protocol for your site
twitter_username: hey_beach
github_username:  jmbeach

# Build settings
markdown: kramdown
